/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rft;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author flash
 */
public class PagamentosTela extends javax.swing.JFrame {

    /**
     * Creates new form PagamentosTela
     */
    public PagamentosTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaP = new javax.swing.JTable();
        btnConfirmar = new javax.swing.JButton();
        fieldBusca = new javax.swing.JTextField();
        btnDeletar = new javax.swing.JButton();
        btnField = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Avignon Pro", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("PAGAMENTOS");

        tabelaP.setModel(montarTabelaP());
        jScrollPane1.setViewportView(tabelaP);

        btnConfirmar.setBackground(new java.awt.Color(255, 255, 0));
        btnConfirmar.setFont(new java.awt.Font("Avignon Pro", 1, 18)); // NOI18N
        btnConfirmar.setText("CONFIRMAR");

        fieldBusca.setBackground(new java.awt.Color(255, 255, 0));
        fieldBusca.setFont(new java.awt.Font("Avignon Pro", 1, 14)); // NOI18N

        btnDeletar.setBackground(new java.awt.Color(255, 255, 0));
        btnDeletar.setFont(new java.awt.Font("Avignon Pro", 1, 18)); // NOI18N
        btnDeletar.setText("DELETAR");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnField.setBackground(new java.awt.Color(255, 255, 0));
        btnField.setFont(new java.awt.Font("Avignon Pro", 1, 18)); // NOI18N
        btnField.setText("CONFIRMAR");
        btnField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Avignon Pro", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("PESQUISAR:");

        btnCadastrar.setBackground(new java.awt.Color(255, 255, 0));
        btnCadastrar.setFont(new java.awt.Font("Avignon Pro", 1, 18)); // NOI18N
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(fieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(292, 292, 292))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(296, 296, 296))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
        CPagamentos cp = new CPagamentos();
        cp.setVisible(true);
        cp.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        
     int linhaSelecionada = tabelaP.getSelectedRow();

    if (linhaSelecionada >= 0) {
        String nome = tabelaP.getValueAt(linhaSelecionada, 0).toString(); 

        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir esse registro?");
        if (resposta == JOptionPane.YES_OPTION) {
            if (LoginFuncao.excluirp(nome)) {
                JOptionPane.showMessageDialog(null, "Registro excluído com sucesso.");
                tabelaP.setModel(montarTabelaP()); 
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao excluir registro.");
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir.");
    }   
        
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFieldActionPerformed
        
        String busca = fieldBusca.getText().trim(); 

        if (busca.isEmpty()) {
            tabelaP.setModel(montarTabelaP());
        } else {
            tabelaP.setModel(montarTabelaBuscaP(busca));
        }  
        
    }//GEN-LAST:event_btnFieldActionPerformed

     private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {                                       
       
       tabelaP.setModel(montarTabelaP());
        jScrollPane1.setViewportView(tabelaP); 
        
    }   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagamentosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagamentosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagamentosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagamentosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagamentosTela().setVisible(true);
            }
        });
    }
    
    private DefaultTableModel montarTabelaP() {
        LoginFuncao dao = new LoginFuncao();
        String[] colunas = {"Nome", "Tipo Plano", "Valor", "Pago"};

       
        DefaultTableModel tabela = new DefaultTableModel(colunas, 0);
        
        

        List<Pagamentos> lista = LoginFuncao.listarPagamentos();
        

        for (int i = 0; i < lista.size(); i++) {
            Pagamentos pa = lista.get(i);

            String[] linha = {
                
                pa.getNome(),
                pa.getTipoplano(),
                Integer.toString(pa.getValor()),
                pa.getPago()
                
                
            };
            tabela.addRow(linha);
        }
        
        return tabela;
    }
    
     private DefaultTableModel montarTabelaBuscaP(String busca) {
        String[] colunas = {"Nome", "Tipo Plano", "Valor", "Pago"};

        //Criamos a tabela
        DefaultTableModel tabela = new DefaultTableModel(colunas, 0);

        List<Pagamentos> lista = LoginFuncao.buscarPorNomeP(busca);

        for (int i = 0; i < lista.size(); i++) {
             Pagamentos pa = lista.get(i);

            String[] linha = {
                
               pa.getNome(),
                pa.getTipoplano(),
                Integer.toString(pa.getValor()),
                pa.getPago()
                
            };
            tabela.addRow(linha);
        }

        if (tabela.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Nenhum aluno encontrado com esse nome!", "Filtro", JOptionPane.INFORMATION_MESSAGE);
        }

        return tabela;
    }
    
    private int getPosicao() {
        int posicao = tabelaP.getSelectedRow();
        if (posicao <= -1) {
            JOptionPane.showMessageDialog(null, "Selecione um item para excluir.");
        }
        return Integer.parseInt((String) tabelaP.getValueAt(posicao, 0));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnField;
    private javax.swing.JTextField fieldBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaP;
    // End of variables declaration//GEN-END:variables
}
